{
 "title": "DC Fabric Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Fabric", "query": { "query": "label_values(source)" } },
   {
    "name": "FabricServices",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   },
   { "name": "DCI", "query": { "query": "label_values(source)" } },
   {
    "name": "DCIServices",
    "query": {
     "query": "label_values(vpls_service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DC Fabric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DC Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:IN"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:OUT"
    },
    {
     "expr": "rate(gnmic_sros_if_stats_in_octets[10s])*8",
     "legendFormat": "{{source}}:{{interface_name}}:IN"
    },
    {
     "expr": "rate(gnmic_sros_if_stats_out_octets[10s])*8",
     "legendFormat": "{{source}}:{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "Network Telemetry",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 35, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "gnmic_srl_if_oper_state_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    },
    {
     "expr": "gnmic_sros_if_oper_state_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    },
    {
     "expr": "rate(gnmic_sros_if_stats_in_octets[10s])*8",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "rate(gnmic_sros_if_stats_out_octets[10s])*8",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": "Front panel view",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 29, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "gnmic_srl_if_oper_state_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    },
    {
     "expr": "gnmic_sros_if_oper_state_oper_state",
     "legendFormat": "{{source}}:{{port_port_id}}"
    }
   ]
  },
  { "title": "$Fabric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_ipv4_routes_active_routes{network_instance_name=\"default\",source=\"$Fabric\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_total_routes{network_instance_name=\"default\",source=\"$Fabric\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$Fabric\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_up_peers{network_instance_name=\"default\",source=\"$Fabric\"}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "gnmic_srl_bgp_stats_total_peers{network_instance_name=\"default\",source=\"$Fabric\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "gnmic_srl_bgp_stats_disabled_peers{network_instance_name=\"default\",source=\"$Fabric\"}",
     "legendFormat": "Disabled Peers"
    },
    {
     "expr": "gnmic_sros_bgp_stats_peers{router_router_name=\"Base\",source=\"$DCI\"}",
     "legendFormat": "Total Peers"
    }
   ]
  },
  {
   "title": "Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_in_bps{source=\"$Fabric\"}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_out_bps{source=\"$Fabric\"}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_total_received_routes{network_instance_name=\"default\",source=\"$Fabric\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "gnmic_srl_bgp_stats_total_active_routes{network_instance_name=\"default\",source=\"$Fabric\"}",
     "legendFormat": "Total Active Routes"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnmic_srl_cpu_instant{source=\"$Fabric\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "gnmic_srl_mem_free{source=\"$Fabric\"}",
     "legendFormat": "Free "
    },
    {
     "expr": "gnmic_srl_mem_utilization{source=\"$Fabric\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "gnmic_srl_mem_reserved{source=\"$Fabric\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "gnmic_srl_mem_physical{source=\"$Fabric\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Service: $FabricServices",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "gnmic_srl_net_instance_oper_state{network_instance_name='$FabricServices'}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "targets": [
    {
     "expr": "gnmic_srl_apps_pid{source='$Fabric'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  { "title": "$DCI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gnmic_sros_ipv4_stats_direct_active_routes{router_router_name=\"Base\",source=\"$DCI\"}) + sum(gnmic_sros_ipv4_stats_bgp_active_routes{router_router_name=\"Base\",source=\"$DCI\"})",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "gnmic_sros_ipv4_stats_bgp_available_routes{router_router_name=\"Base\",source=\"$DCI\"}",
     "legendFormat": "IPv4 BGP Available Routes"
    },
    {
     "expr": "gnmic_sros_bgp_routes_stats_active_routes{router_router_name=\"Base\",source=\"$DCI\"}",
     "legendFormat": "IPv4 BGP Active Routes"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gnmic_sros_bgp_stats_peer_groups{router_router_name=\"Base\",source=\"$DCI\"})*sum(gnmic_sros_bgp_up_peers_up_peers{router_router_name=\"Base\",source=\"$DCI\"})",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "gnmic_sros_bgp_stats_peers{router_router_name=\"Base\",source=\"$DCI\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "sum(gnmic_sros_bgp_stats_peers{router_router_name=\"Base\",source=\"$DCI\"}) - sum(gnmic_sros_bgp_stats_peer_groups{router_router_name=\"Base\",source=\"$DCI\"})*sum(gnmic_sros_bgp_up_peers_up_peers{router_router_name=\"Base\",source=\"$DCI\"})",
     "legendFormat": "Disabled Peers"
    },
    {
     "expr": "gnmic_sros_bgp_stats_peer_groups{router_router_name=\"Base\",source=\"$DCI\"}",
     "legendFormat": "Total Groups "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_if_stats_in_octets{source=\"$DCI\"}[10s])*8",
     "legendFormat": "{{port_port_id}}:IN"
    },
    {
     "expr": "rate(gnmic_sros_if_stats_out_octets{source=\"$DCI\"}[10s])*8",
     "legendFormat": "{{port_port_id}}:OUT"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_ipv4_stats_bgp_active_routes{router_router_name=\"Base\",source=\"$DCI\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "sum(gnmic_sros_bgp_routes_active_active{router_router_name=\"Base\",source=\"$DCI\"}) + sum(gnmic_sros_ipv4_stats_direct_active_routes{router_router_name=\"Base\",source=\"$DCI\"})",
     "legendFormat": "Total Active Routes"
    },
    {
     "expr": "gnmic_sros_evpn_routes_remote_active_routes{router_router_name=\"Base\",source=\"$DCI\"}",
     "legendFormat": "Evpn Active Routes"
    },
    {
     "expr": "gnmic_sros_vxlan_learned_macs_bgp_evpn{vpls_service_name=\"1\", source='$DCI'}",
     "legendFormat": "MAC/IP Routes"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnmic_sros_cpu_cpu_usage{source=\"$DCI\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "gnmic_sros_mem_available_memory{source=\"$DCI\"}",
     "legendFormat": "Free "
    },
    {
     "expr": "gnmic_sros_mem_total_in_use{source=\"$Fabric\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "gnmic_sros_mem_current_total_size{source=\"$DCI\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "gnmic_sros_mem_in_use{source=\"$DCI\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Service: $DCIServices",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "gnmic_sros_vpls_instance_oper_state_oper_state{}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "VTEPs Active",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 66 },
   "targets": [
    {
     "expr": "gnmic_sros_vxlan_vteps_oper_state{source=\"$DCI\"}",
     "legendFormat": "{{tep_ip_address}}"
    }
   ]
  },
  {
   "title": "VXLAN Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 66 },
   "targets": [
    {
     "expr": "gnmic_sros_evpn_vxlan_vni_vni{source='$DCI'}",
     "legendFormat": "{{instance_vxlan_instance}}"
    }
   ]
  }
 ]
}